# coding=utf-8
from __future__ import absolute_import

class SettingsKeys():

	## General
	SETTINGS_KEY_PLUGIN_DEPENDENCY_CHECK = "pluginCheckActivated"
	SETTINGS_KEY_SHOW_PRINTJOB_DIALOG_AFTER_PRINT = "showPrintJobDialogAfterPrint"
	SETTINGS_KEY_SHOW_PRINTJOB_DIALOG_AFTER_PRINT_JOB_ID = "showPrintJobDialogAfterPrint_jobId"

	SETTINGS_KEY_SHOWPRINTJOBDIALOGAFTERPRINT_MODE = "showPrintJobDialogAfterPrintMode"
	KEY_SHOWPRINTJOBDIALOGAFTERPRINT_MODE_ALWAYS = "always"
	KEY_SHOWPRINTJOBDIALOGAFTERPRINT_MODE_SUCCESSFUL = "successful"

	SETTINGS_KEY_CAPTURE_PRINTJOBHISTORY_MODE = "capturePrintJobHistoryMode"
	KEY_CAPTURE_PRINTJOBHISTORY_MODE_NONE = "none"
	KEY_CAPTURE_PRINTJOBHISTORY_MODE_ALWAYS = "always"
	KEY_CAPTURE_PRINTJOBHISTORY_MODE_SUCCESSFUL = "successful"

	## Camera
	SETTINGS_KEY_TAKE_SNAPSHOT_AFTER_PRINT = "takeSnapshotAfterPrint"
	SETTINGS_KEY_TAKE_PLUGIN_THUMBNAIL_AFTER_PRINT = "takePluginThumbnailAfterPrint"

	SETTINGS_KEY_TAKE_TEMPERATURE_FROM_PREHEAT = "takeTemperatureFromPreHeatPlugin"
	SETTINGS_KEY_DELAY_READING_TEMPERATURE_FROM_PRINTER = "delayReadingTemperatureFromPrinter"

	## Export / Import
	SETTINGS_KEY_IMPORT_CSV_MODE = "importCSVMode"
	KEY_IMPORTCSV_MODE_REPLACE = "replace"
	KEY_IMPORTCSV_MODE_APPEND = "append"

	## Storage
	SETTINGS_KEY_DATABASE_PATH = "databaseFileLocation"
	SETTINGS_KEY_SNAPSHOT_PATH = "snapshotFileLocation"

	## Debugging
	SETTINGS_KEY_SQL_LOGGING_ENABLED = "sqlLoggingEnabled"
